bookmark = [
	{ key = "r",	path = "/" },
	{ key = "E",	path = "/etc" },
	{ key = "P",	path = "~/jack" },
	{ key = "e",	path = "~/.config/emacs" },

	{ key = "c",	path = "~/.config" },
	{ key = "s",	path = "~/Pictures/Screenshots" },
	{ key = "d",	path = "~/Downloads" },
	{ key = "p",	path = "~/Downloads/papers" },
	{ key = "b",	path = "~/Downloads/papers/books" },
	{ key = "j",	path = "~/Documents/2023" },
	{ key = "h",	path = "~/" },
	{ key = "r",	path = "~/jackdatabank/jackhome/projects/sheepDimension/repos/" },
]
